options:
  docker: true
 
pipelines:
  branches:
    master:
      - step:
          name: Build Docker Image (Prod)
          image: tstrohmeier/awscli:3.8.3
          script:
            - echo "Logging into AWS ECR..."
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 794038237159.dkr.ecr.us-west-1.amazonaws.com
            - echo "Building docker image.."
            - docker build --no-cache -t 794038237159.dkr.ecr.us-west-1.amazonaws.com/webhook-ingestion-prod -f services/webhook-ingestion/Dockerfile .
            - echo "Pushing docker image to AWS ECR..."
            - docker push 794038237159.dkr.ecr.us-west-1.amazonaws.com/webhook-ingestion-prod 
            - docker build --no-cache -t 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-downloader-prod -f services/document-downloader/Dockerfile .
            - echo "Pushing docker second image to AWS ECR..."
            - docker push 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-downloader-prod
            - docker build --no-cache -t 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-parser-prod -f services/document-parser/Dockerfile .
            - echo "Pushing docker third image to AWS ECR..."
            - docker push 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-parser-prod
      - step:
          name: Trigger Deployment Pipeline
          image: curlimages/curl
          script:
            - echo "Triggering pipeline in another repository..."
            - |
              curl -X POST -u leen.a:$APP_PASSWORD \
              -H "Content-Type: application/json" \
              -d '{
                    "target": {
                      "type": "pipeline_ref_target",
                      "ref_type": "branch",
                      "ref_name": "main",
                      "selector": {
                        "type": "custom",
                        "pattern": "deployment"
                      }
                    }
                  }' \
              https://api.bitbucket.org/2.0/repositories/wuduh/webhook-ingestion-prod-deployment/pipelines/

            - |
              curl -X POST -u leen.a:$APP_PASSWORD \
              -H "Content-Type: application/json" \
              -d '{
                    "target": {
                      "type": "pipeline_ref_target",
                      "ref_type": "branch",
                      "ref_name": "main",
                      "selector": {
                        "type": "custom",
                        "pattern": "deployment"
                      }
                    }
                  }' \
              https://api.bitbucket.org/2.0/repositories/wuduh/document-downloader-prod-deployment/pipelines/

            - |
              curl -X POST -u leen.a:$APP_PASSWORD \
              -H "Content-Type: application/json" \
              -d '{
                    "target": {
                      "type": "pipeline_ref_target",
                      "ref_type": "branch",
                      "ref_name": "main",
                      "selector": {
                        "type": "custom",
                        "pattern": "deployment"
                      }
                    }
                  }' \
              https://api.bitbucket.org/2.0/repositories/wuduh/document-parser-prod-deployment/pipelines/
    stg:
      - step:
          name: Build Docker Image (STG)
          image: tstrohmeier/awscli:3.8.3
          script:
            - echo "Logging into AWS ECR..."
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 794038237159.dkr.ecr.us-west-1.amazonaws.com
            - echo "Building docker image.."
            - docker build --no-cache -t 794038237159.dkr.ecr.us-west-1.amazonaws.com/webhook-ingestion-stg -f services/webhook-ingestion/Dockerfile .
            - echo "Pushing docker image to AWS ECR..."
            - docker push 794038237159.dkr.ecr.us-west-1.amazonaws.com/webhook-ingestion-stg 
            - docker build --no-cache -t 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-downloader-stg -f services/document-downloader/Dockerfile .
            - echo "Pushing docker second image to AWS ECR..."
            - docker push 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-downloader-stg
            - docker build --no-cache -t 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-parser-stg -f services/document-parser/Dockerfile .
<<<<<<< HEAD
            - echo "Pushing docker third image to AWS ECR..."
=======
            - echo "Pushing docker second image to AWS ECR..."
>>>>>>> 0628449c8369b2504b1a7412d1ff37cb662eb042
            - docker push 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-parser-stg
      - step:
          name: Trigger Deployment Pipeline
          image: curlimages/curl
          script:
            - echo "Triggering pipeline in another repository..."
            - |
              curl -X POST -u leen.a:$APP_PASSWORD \
              -H "Content-Type: application/json" \
              -d '{
                    "target": {
                      "type": "pipeline_ref_target",
                      "ref_type": "branch",
                      "ref_name": "main",
                      "selector": {
                        "type": "custom",
                        "pattern": "deployment"
                      }
                    }
                  }' \
              https://api.bitbucket.org/2.0/repositories/wuduh/webhook-ingestion-stg-deployment/pipelines/

            - |
              curl -X POST -u leen.a:$APP_PASSWORD \
              -H "Content-Type: application/json" \
              -d '{
                    "target": {
                      "type": "pipeline_ref_target",
                      "ref_type": "branch",
                      "ref_name": "main",
                      "selector": {
                        "type": "custom",
                        "pattern": "deployment"
                      }
                    }
                  }' \
              https://api.bitbucket.org/2.0/repositories/wuduh/document-downloader-stg-deployment/pipelines/

            - |
              curl -X POST -u leen.a:$APP_PASSWORD \
              -H "Content-Type: application/json" \
              -d '{
                    "target": {
                      "type": "pipeline_ref_target",
                      "ref_type": "branch",
                      "ref_name": "main",
                      "selector": {
                        "type": "custom",
                        "pattern": "deployment"
                      }
                    }
                  }' \
              https://api.bitbucket.org/2.0/repositories/wuduh/document-parser-stg-deployment/pipelines/
    dev:
      - step:
          name: Build Docker Image (Dev)
          image: tstrohmeier/awscli:3.8.3
          script:
            - echo "Logging into AWS ECR..."
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 794038237159.dkr.ecr.us-west-1.amazonaws.com
            - echo "Building docker image.."
            - docker build --no-cache -t 794038237159.dkr.ecr.us-west-1.amazonaws.com/webhook-ingestion-dev -f services/webhook-ingestion/Dockerfile .
            - echo "Pushing docker image to AWS ECR..."
            - docker push 794038237159.dkr.ecr.us-west-1.amazonaws.com/webhook-ingestion-dev 
            - docker build --no-cache -t 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-downloader-dev -f services/document-downloader/Dockerfile .
            - echo "Pushing docker second image to AWS ECR..."
            - docker push 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-downloader-dev
            - docker build --no-cache -t 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-parser-dev -f services/document-parser/Dockerfile .
<<<<<<< HEAD
            - echo "Pushing docker third image to AWS ECR..."
=======
            - echo "Pushing docker second image to AWS ECR..."
>>>>>>> 0628449c8369b2504b1a7412d1ff37cb662eb042
            - docker push 794038237159.dkr.ecr.us-west-1.amazonaws.com/document-parser-dev
      - step:
          name: Trigger Deployment Pipeline
          image: curlimages/curl
          script:
            - echo "Triggering pipeline in another repository..."
            - |
              curl -X POST -u leen.a:$APP_PASSWORD \
              -H "Content-Type: application/json" \
              -d '{
                    "target": {
                      "type": "pipeline_ref_target",
                      "ref_type": "branch",
                      "ref_name": "main",
                      "selector": {
                        "type": "custom",
                        "pattern": "deployment"
                      }
                    }
                  }' \
              https://api.bitbucket.org/2.0/repositories/wuduh/webhook-ingestion-dev-deployment/pipelines/

            - |
              curl -X POST -u leen.a:$APP_PASSWORD \
              -H "Content-Type: application/json" \
              -d '{
                    "target": {
                      "type": "pipeline_ref_target",
                      "ref_type": "branch",
                      "ref_name": "main",
                      "selector": {
                        "type": "custom",
                        "pattern": "deployment"
                      }
                    }
                  }' \
              https://api.bitbucket.org/2.0/repositories/wuduh/document-downloader-dev-deployment/pipelines/

            - |
              curl -X POST -u leen.a:$APP_PASSWORD \
              -H "Content-Type: application/json" \
              -d '{
                    "target": {
                      "type": "pipeline_ref_target",
                      "ref_type": "branch",
                      "ref_name": "main",
                      "selector": {
                        "type": "custom",
                        "pattern": "deployment"
                      }
                    }
                  }' \
              https://api.bitbucket.org/2.0/repositories/wuduh/document-parser-dev-deployment/pipelines/